What I want to do now is take the Adjusted Close column in all the csv files and form one big DataFrame with them, where the 'Date' is the the index (rows) and the different companies are the columns.

In [1]:
import pandas as pd
import pickle
import matplotlib.pyplot as plt
from matplotlib import style

style.use('ggplot')

In [2]:
def combine_data():
    with open("sp500tickers.pickle", "rb") as f:
        tickers = pickle.load(f)
    main_df = pd.DataFrame()
    
    for count, ticker in enumerate(tickers):
        df = pd.read_csv('stock_dfs/{}.csv'.format(ticker))
        df.set_index('Date', inplace=True)
        df.rename(columns={'Adj Close':ticker}, inplace=True)
        df.drop(['Open','High','Low','Close','Volume'], axis=1, inplace=True) #axis default is 0, but this returns an error
        
        if main_df.empty: #now we join all these 'Adj Close' DataFrames together.
             main_df = df
        else:
            main_df = main_df.join(df, how='outer') #outer joining tables like in sql (so we don't lose data if some rows are missing from some for some tickers).
        if count%10 == 0:
            print(count) # So every 10th ticker in the list gets printed just to check we get roughly all the companies (without having to go through the entire list)
    print(main_df.head())
    main_df.to_csv('sp500_joined_closes.csv')

In [7]:
combine_data()

0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
                  MMM       ABT  ABBV      ABMD  ACN      ATVI       ADBE  \
Date
1999-12-31        NaN       NaN   NaN       NaN  NaN       NaN        NaN
2000-01-03  28.056503  9.595666   NaN  18.25000  NaN  1.227554  16.274673
2000-01-04  26.941685  9.321495   NaN  17.81250  NaN  1.190215  14.909401
2000-01-05  27.722048  9.304364   NaN  18.00000  NaN  1.194882  15.204173
2000-01-06  29.951698  9.629930   NaN  18.03125  NaN  1.171544  15.328290

               AMD  AAP        AES  ...  WYNN       XEL        XRX       XLNX  \
Date                                ...
1999-12-31     NaN  NaN        NaN  ...   NaN       NaN        NaN        NaN
2000-01-03  15.500  NaN  28.031807  ...   NaN  7.682479  42.847652  33.169758
2000-01-04  14.625  NaN  26.920206  ...   NaN  7.859379  40.854725  32.415897
2000-01-05  15.000  NaN  27.210192  ...   NaN  8.162634  42.958355  31.706371
2000-01-06  16.000  NaN  27.427675  ...   NaN  8.086820  42.072613  28.957006

            XYL       YUM       ZBRA  ZBH       ZION  ZTS
Date
1999-12-31  NaN       NaN        NaN  NaN        NaN  NaN
2000-01-03  NaN  4.988526  25.027779  NaN  40.342747  NaN
2000-01-04  NaN  4.888254  24.666666  NaN  38.389206  NaN
2000-01-05  NaN  4.913321  25.138889  NaN  38.343781  NaN
2000-01-06  NaN  4.871542  23.777779  NaN  38.888947  NaN

[5 rows x 505 columns]

In [3]:
df=pd.read_csv('sp500_joined_closes.csv')

In [4]:
df_corr = df.corr() #the .corr() attribute measures the correlation between every pair of companies (columns).
df_corr.head()

,MMM,ABT,ABBV,ABMD,ACN,ATVI,ADBE,AMD,AAP,AES,...,WYNN,XEL,XRX,XLNX,XYL,YUM,ZBRA,ZBH,ZION,ZTS
MMM,1.000000,0.912468,0.703508,0.935858,0.930512,0.940576,0.887741,0.801984,0.957021,0.363715,...,0.352591,0.933637,-0.301366,0.915510,0.759456,0.968508,0.904322,0.954504,-0.318859,0.451177
ABT,0.912468,1.000000,0.930128,0.973527,0.996428,0.989927,0.996640,0.967327,0.912915,0.521736,...,0.029810,0.996446,-0.460481,0.986674,0.973139,0.971842,0.996995,0.958142,-0.381944,0.997986
ABBV,0.703508,0.930128,1.000000,0.941107,0.954656,0.968630,0.931804,0.891360,0.562779,0.875058,...,-0.627220,0.940121,-0.540235,0.926157,0.967115,0.924943,0.938782,0.916988,0.099910,0.930933
ABMD,0.935858,0.973527,0.941107,1.000000,0.978190,0.983787,0.970519,0.927263,0.908514,0.514963,...,0.090765,0.974808,-0.410122,0.976415,0.953327,0.965547,0.973597,0.945831,-0.300102,0.873090
ACN,0.930512,0.996428,0.954656,0.978190,1.000000,0.993810,0.990182,0.956806,0.932163,0.887884,...,0.079788,0.998728,-0.444403,0.993679,0.988413,0.983245,0.992428,0.969538,-0.359851,0.993290

It ocurred to me this morning that measuring the correlation between the adjusted close prices probably isn't the best way to measure correlation. This is because the adjusted close price is a raw price, so perhaps if I made a DataFrame all all the returns of all the companies and then measured the correlation between the RETURNS, this would make a lot more sense!